site_name: Mi KB - Cursos Tecnología
site_description: Knowledge Base - SEO, Cursos, Apuntes
site_author: Tu Nombre

theme:
  name: material
  custom_dir: overrides
  language: es
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    

plugins:
  - search:
      lang: es
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - minify:
      minify_html: true
  - mermaid2
  

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.admonition

nav:
  - Inicio: index.md
  - SEO:
      - Conceptos Básicos SEO: SEO/01-conceptos_basicos_seo.md
      - Indexación y Rastreo: SEO/02-indexacion_y_rastreo.md
      - ejemplo diagrama: SEO/ejemplo-diagrama.md




      
  - GUIA: 
      
      - Tips de Redacción: GUIA/01-tips.md
      
      - Plantillas:      
        - Plantilla Apuntes: GUIA/02-plantilla_apuntes.md
        - Plantilla Checklist: GUIA/03-plantilla_checklist.md
        - Plantilla Diagrama Mermaid: GUIA/04-plantilla_diagrama_mermaid.md
        - Plantilla Comparativa/Tabla: GUIA/05-plantilla_comparativa_tabla.md
        - Plantilla Concepto + Checklist: GUIA/06-plantilla_concepto_checklist.md
        - Sintesis de plantillas: GUIA/plantilla_resumen_sintesis.md
        - cornell: GUIA/cornell.md
      - Otros:
        - Referencia Rápida: GUIA/08-REFERENCIA_RAPIDA.md
        - Guía Nuevo Proyecto: GUIA/09-GUIA_PROYECTO_NUEVO.md
      

      

extra_javascript:
  - js/pdf-export.js

extra_css:
  - css/custom.css

